import subprocess
import os
from datetime import datetime

class ShellExecutor:
    def __init__(self):
        self.name = "module.execution.shell"

    def can_execute(self, task_spec):
        # Shell executor can handle 'task' kind with 'shell' tag or if explicitly hinted
        meta = task_spec.get("meta", {})
        actor = task_spec.get("actor", {})
        return meta.get("kind") == "task" and actor.get("executor_hint") == self.name

    def execute(self, task_spec):
        """
        Execute the task instructions via shell.
        For v0, we assume 'Instruction' is passed in extensions or we parse intent.
        """
        task_id = task_spec["id"]
        start_time = datetime.now().astimezone().isoformat()
        
        # In a real scenario, we'd have a 'steps' field. 
        # For this demo, let's just create a dummy output.
        outputs = task_spec["artifacts"].get("outputs", [])
        observed_writes = []
        
        for out in outputs:
            path = os.path.expanduser(out["path"])
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, 'w') as f:
                f.write(f"Generated by ShellExecutor for task {task_id}")
            observed_writes.append({"path": path})

        return {
            "task_id": task_id,
            "version": "1.0",
            "executor": {
                "name": self.name,
                "instance_id": f"shell_{os.getpid()}",
                "started_at": start_time,
                "ended_at": datetime.now().astimezone().isoformat()
            },
            "outcome": {
                "status": "completed",
                "exit_code": 0,
                "summary": f"Generated {len(outputs)} output files."
            },
            "artifacts": {
                "outputs": [
                    {"path": w["path"], "hash": f"sha256:{self._hash_file(w['path'])}"} 
                    for w in observed_writes
                ],
                "deleted": []
            },
            "evidence": {
                "stdout": "Success",
                "stderr": ""
            },
            "gates": {
                "observed_fs_writes": observed_writes,
                "observed_processes": [
                    {"cmd": "write_file", "ended_clean": True}
                ]
            }
        }

    def _hash_file(self, path):
        import hashlib
        sha256_hash = hashlib.sha256()
        with open(path, "rb") as f:
            for byte_block in iter(lambda: f.read(4096), b""):
                sha256_hash.update(byte_block)
        return sha256_hash.hexdigest()
