#!/usr/bin/env zsh
# tools/ops/decision_box.zsh — Record of Truth (Decision Artifact Generator)
# Version: v1.1
# Usage: ./decision_box.zsh --title "..." --why "..." --risk low|med|high --scope "..." --links "..."

set -euo pipefail

# ── 1. Path Resolution ──────────────────────────────────────────────
ROOT="${0:A:h:h:h}"
DECISION_DIR="$ROOT/g/state/decision_box"
ACTIVITY_FEED="${LUKA_ACTIVITY_FEED_JSONL:-$ROOT/observability/logs/activity_feed.jsonl}"

mkdir -p "$DECISION_DIR"

# ── 2. Argument Parsing ────────────────────────────────────────────
TITLE=""
WHY=""
RISK="low"
SCOPE=""
LINKS=""

# Simple manual parser for --long-args
while [[ $# -gt 0 ]]; do
  case $1 in
    --title) TITLE="$2"; shift 2 ;;
    --why)   WHY="$2"; shift 2 ;;
    --risk)  RISK="$2"; shift 2 ;;
    --scope) SCOPE="$2"; shift 2 ;;
    --links) LINKS="$2"; shift 2 ;;
    *) echo "Unknown argument: $1" >&2; exit 1 ;;
  esac
done

if [[ -z "$TITLE" || -z "$WHY" ]]; then
  echo "ERROR: --title and --why are mandatory." >&2
  exit 1
fi

# ── 3. Artifact Metadata ───────────────────────────────────────────
TS=$(date -u +"%Y%m%dT%H%M%SZ")
TS_ISO=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
BASE_NAME="${TS}_decision"
JSON_FILE="$DECISION_DIR/${BASE_NAME}.json"
MD_FILE="$DECISION_DIR/${BASE_NAME}.md"

# ── 4. Generate Human-Readable Markdown ────────────────────────────
# Write to temp first for integrity
TMP_MD=$(mktemp)
cat <<EOF > "$TMP_MD"
# Decision: $TITLE

- **Timestamp**: $TS_ISO
- **Risk Level**: ${(U)RISK}
- **Author**: ${AGENT_ID:-gmx}

## Why
$WHY

## Scope
$SCOPE

## Links / Refs
$LINKS

---
*Generated by Decision Box v1 (Fail-Closed Evidence)*
EOF

MD_SHA256=$(shasum -a 256 "$TMP_MD" | awk '{print $1}')

# ── 5. Activity Feed Append (Best Effort) ──────────────────────────
ACTIVITY_OK="false"
ACTIVITY_REASON="N/A"
DISPLAY_FEED_PATH="${ACTIVITY_FEED#$ROOT/}"

EVENT_TS_MS=$(python3 -c 'import time; print(int(time.time() * 1000))')
# Escape quotes for JSON string
TITLE_ESC=$(echo "$TITLE" | sed 's/"/\\"/g')
EVENT_JSON="{\"ts_utc\": \"$TS_ISO\", \"ts_epoch_ms\": $EVENT_TS_MS, \"category\": \"governance\", \"action\": \"decision\", \"emit_mode\": \"manual_invoke\", \"title\": \"Decision: $TITLE_ESC\", \"status_badge\": \"SIGNED\", \"evidence\": {\"file\": \"g/state/decision_box/${BASE_NAME}.json\"}}"

if [[ -f "$ACTIVITY_FEED" && -w "$ACTIVITY_FEED" ]]; then
  if echo "$EVENT_JSON" >> "$ACTIVITY_FEED"; then
    ACTIVITY_OK="true"
  else
    ACTIVITY_REASON="write_failed"
  fi
else
  ACTIVITY_REASON="feed_missing_or_readonly"
fi

# ── 6. Generate JSON Artifact ──────────────────────────────────────
# Escape all variables for JSON
WHY_ESC=$(echo "$WHY" | sed 's/"/\\"/g')
SCOPE_ESC=$(echo "$SCOPE" | sed 's/"/\\"/g')
LINKS_ESC=$(echo "$LINKS" | sed 's/"/\\"/g')

TMP_JSON=$(mktemp)
cat <<EOF > "$TMP_JSON"
{
  "schema_version": "decision_box_v1",
  "ts": "$TS_ISO",
  "title": "$TITLE_ESC",
  "why": "$WHY_ESC",
  "risk": "$RISK",
  "scope": "$SCOPE_ESC",
  "links": "$LINKS_ESC",
  "artifacts": {
    "md": "g/state/decision_box/${BASE_NAME}.md",
    "md_sha256": "$MD_SHA256"
  },
  "activity_append": {
    "attempted": true,
    "ok": $ACTIVITY_OK,
    "path": "$DISPLAY_FEED_PATH",
    "reason": "$ACTIVITY_REASON"
  }
}
EOF

# Calculate JSON SHA256 and add as a metadata field
JSON_SHA256=$(shasum -a 256 "$TMP_JSON" | awk '{print $1}')
FINAL_JSON=$(mktemp)
# Inject the final sha256 before the last brace using a safer method
sed '$d' "$TMP_JSON" > "$FINAL_JSON"
echo "  ,\"json_sha256\": \"$JSON_SHA256\"" >> "$FINAL_JSON"
echo "}" >> "$FINAL_JSON"

# ── 7. Atomic Move ───────────────────────────────────────────────
mv "$TMP_MD" "$MD_FILE"
mv "$FINAL_JSON" "$JSON_FILE"
rm -f "$TMP_JSON"

echo "✅ Decision Artifacts Created:"
echo "   MD:   g/state/decision_box/${BASE_NAME}.md"
echo "   JSON: g/state/decision_box/${BASE_NAME}.json"
echo "   Feed: $ACTIVITY_OK ($ACTIVITY_REASON)"
