#!/usr/bin/env python3
"""
Shim Generator: Reads core_brain/catalog/registry.yaml and creates wrapper scripts in system/bin/
Usage: python3 core_brain/ops/generate_shims.py
"""
import os
import sys
import yaml
from pathlib import Path

# Path Logic:
# __file__ = 0luka/core_brain/ops/generate_shims.py
# parent = ops
# parent.parent = core_brain
# parent.parent.parent = 0luka (ROOT)

ROOT = Path(__file__).resolve().parent.parent.parent
CORE_BRAIN = ROOT / "core_brain"
REGISTRY_PATH = CORE_BRAIN / "catalog/registry.yaml"
BIN_DIR = ROOT / "system/bin"
LOOKUP_TOOL = CORE_BRAIN / "ops/catalog_lookup.zsh"

def main():
    if not REGISTRY_PATH.exists():
        print(f"Error: Registry not found at {REGISTRY_PATH}")
        sys.exit(1)
    
    if not BIN_DIR.exists():
        os.makedirs(BIN_DIR, exist_ok=True)
        print(f"Created bin directory: {BIN_DIR}")

    with open(REGISTRY_PATH, 'r') as f:
        data = yaml.safe_load(f)
    
    tools = data.get("tools", [])
    count = 0

    shim_template = """#!/bin/zsh
# 0luka Catalog Shim: {name}
# Auto-generated by shim generator (Core Brain)

# Resolve using Core Brain Lookup Tool
REAL_PATH=$({lookup_tool} {name})
EXIT_CODE=$?

if [[ $EXIT_CODE -ne 0 ]]; then
    echo "Shim Error: Could not resolve tool '{name}' via catalog." >&2
    exit 1
fi

# Execute the resolved tool with original arguments
exec "$REAL_PATH" "$@"
"""

    for tool in tools:
        name = tool.get("name")
        if not name:
            continue
        
        shim_path = BIN_DIR / name
        content = shim_template.format(
            name=name,
            lookup_tool=LOOKUP_TOOL
        )
        
        with open(shim_path, 'w') as f:
            f.write(content)
        
        # Make executable
        os.chmod(shim_path, 0o755)
        count += 1
        print(f"Generated shim: {name}")

    print(f"Success: Generated {count} shims in {BIN_DIR}")

if __name__ == "__main__":
    main()
